---
version: "3.3"

services:
  primary:
    image: mongo:4.2
    command:
      - --replSet
      - mongo-set
    ports:
      - "27017:27017"
    networks:
      - mongonet
    deploy:
      placement:
        constraints:
          - node.labels.type == primary
          - node.role == worker
  replica1:
    image: mongo:4.2
    command:
      - --replSet
      - mongo-set
    ports:
      - "27018:27017"
    networks:
      - mongonet
    deploy:
      placement:
        constraints:
          - node.labels.type != primary
          - node.role == worker

  replica2:
    image: mongo:4.2
    command:
      - --replSet
      - mongo-set
    ports:
      - "27019:27017"
    networks:
      - mongonet
    deploy:
      placement:
        constraints:
          - node.labels.type != primary
          - node.role == worker
networks:
  mongonet:

